//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ftn.Android.backend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FTNBackendContainer : DbContext
    {
        public FTNBackendContainer()
            : base("name=FTNBackendContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LocatableDTO> LocatableDTOes { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<UserDto> UserDtoes { get; set; }
    }
}
