//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ftn.Android.backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDto()
        {
            this.CreatedLocatableDTO = new HashSet<LocatableDTO>();
            this.ConfirmedLocatable = new HashSet<LocatableDTO>();
        }
    
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public double Longittude { get; set; }
        public double Lattitude { get; set; }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocatableDTO> CreatedLocatableDTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocatableDTO> ConfirmedLocatable { get; set; }
    }
}
